apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: msb 
  namespace: onap 
spec:
  rules:
  - services: ["*"]
    methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-service-msb
  namespace: onap 
spec:
  subjects:
  - user: "cluster.local/ns/onap/sa/msb"
  roleRef:
    kind: ServiceRole
    name: "msb"
